// Values in this file are autogenerated by build scripts -- manual changes may be discarded
namespace Test
open System.Reflection
open System.Runtime.CompilerServices


[<assembly: AssemblyTitle("Interstellar.macOS.WebKit.FullFramework")>]
[<assembly: AssemblyDescription("Cross-platform F# browser library")>]

#if DEBUG
[<assembly: AssemblyConfiguration("Debug")>]
#else
[<assembly: AssemblyConfiguration("Release")>]
#endif

[<assembly: AssemblyCompany("Interstellar Contributors")>]
[<assembly: AssemblyProduct("Interstellar.macOS.WebKit.FullFramework")>]
[<assembly: AssemblyCopyright("© John Wostenberg 2019-2021")>]
//[<assembly: AssemblyTrademark("")>]

// The assembly version has the format {Major}.{Minor}.{Build}.{Revision}

[<assembly: AssemblyVersion("0.3.3")>]
[<assembly: AssemblyInformationalVersion("0.3.3")>]
[<assembly: AssemblyFileVersion("0.3.3.0")>]

//[<assembly: AssemblyDelaySign(false)>]
//[<assembly: AssemblyKeyFile("")>]

()
